version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
#    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "1050:80"
      - "443:443"
    volumes:
      - ./dist/tangerine-home-automator-ui:/var/www
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/ssl
      - ./certs:/var/www/src/assets/certs
