version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
#    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tangerine/nest-ui:/var/www
      - ./docker/conf.d:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
      - ./docker/certs/serveris.local:/ssl
      - ./docker/certs:/var/www/assets/certs
